import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'


export default function Sobre() {
    return (
        <div className="">
            <Head>
                <title>Sobre</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
    )
}